### ISSUE TITLE
Missing/relocated resources

### ISSUE THREAD

**Issue by katergin** [ibm-cloud-docs/openwhisk#199]
`ibmcloud fn package get /whisk.system/cloudant/update-document` finds no resource. Same issue for other actions in the package.

**Comment by kersten1** [comment]
I really apologize for the length of time it has taken me to answer this question! Especially since the answer is pretty straightforward.  `/whisk.system/cloudant/read-document ` is an action so you need to run `ibmcloud fn action get /whisk.system/cloudant/read-document`.  

Please reopen if this did not solve your problem.
